export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const NEW_ITEM_CREATED = "NEW_ITEM_CREATED";
export const CATEGORY_REMOVE_ITEM = "CATEGORY_REMOVE_ITEM";
