export const LIST_ADD_ITEM = 'LIST_ADD_ITEM'
export const LIST_REMOVE_ITEM = 'LIST_REMOVE_ITEM'
export const LIST_TOGGLE_ITEM_QTY = 'LIST_TOGGLE_ITEM_QTY'

export const LIST_ACTIVE = 'LIST_ACTIVE'
export const LIST_MOBILE_TOGGLE = 'LIST_MOBILE_TOGGLE'

export const LIST_TITLE_EDIT = 'LIST_TITLE_EDIT'
export const LIST_RESET_EDIT = 'LIST_RESET_EDIT'

export const LIST_CANCEL_TOGGLE = 'LIST_CANCEL_TOGGLE'
export const LIST_ITEM_CHECK_TOGGLE = 'LIST_ITEM_CHECK_TOGGLE'
